macro(list_subdirs result curdir)
  file(GLOB children RELATIVE ${curdir} ${curdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
      list(APPEND dirlist ${child})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()

macro(add_subdirs subdirs label)
  if(${subdirs})
    set(dirs "${${subdirs}}")
    message("")
    message("${label}")
    message("__________________________________________________________________")
    set(index 1)
    foreach(dir ${dirs})
      message("${index}. ${dir}")
      add_subdirectory(${dir})
      math(EXPR index "${index} + 1")
    endforeach(dir ${dirs})
    message("__________________________________________________________________")
    message("")
  endif()
endmacro()
